import {
  SiCss,
  SiExpress,
  SiGit,
  SiHtml5,
  SiJavascript,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiPython,
  SiReact,
  SiTailwindcss,
  SiVercel,
  SiVscodium,
} from 'react-icons/si';

export const TECHNOLOGIES = [
  {
    id: 'vscode',
    label: 'VS Code',
    color: '#3B82F6',
    Icon: SiVscodium,
    shell: 'outer',
  },
  {
    id: 'git',
    label: 'Git',
    color: '#F97316',
    Icon: SiGit,
    shell: 'middle',
  },
  {
    id: 'linux',
    label: 'Linux',
    color: '#FB7185',
    Icon: SiLinux,
    shell: 'outer',
  },
  {
    id: 'vercel',
    label: 'Vercel',
    color: '#F8FAFC',
    Icon: SiVercel,
    shell: 'outer',
  },
  {
    id: 'python',
    label: 'Python',
    color: '#A78BFA',
    Icon: SiPython,
    shell: 'middle',
  },
  {
    id: 'sql',
    label: 'SQL',
    color: '#818CF8',
    Icon: SiMysql,
    shell: 'inner',
  },
  {
    id: 'react',
    label: 'React',
    color: '#61DAFB',
    Icon: SiReact,
    shell: 'outer',
  },
  {
    id: 'html',
    label: 'HTML5',
    color: '#F97316',
    Icon: SiHtml5,
    shell: 'middle',
  },
  {
    id: 'css',
    label: 'CSS3',
    color: '#38BDF8',
    Icon: SiCss,
    shell: 'middle',
  },
  {
    id: 'next',
    label: 'Next.js',
    color: '#E2E8F0',
    Icon: SiNextdotjs,
    shell: 'middle',
  },
  {
    id: 'tailwind',
    label: 'Tailwind',
    color: '#38BDF8',
    Icon: SiTailwindcss,
    shell: 'outer',
  },
  {
    id: 'node',
    label: 'Node.js',
    color: '#4ADE80',
    Icon: SiNodedotjs,
    shell: 'inner',
  },
  {
    id: 'mongodb',
    label: 'MongoDB',
    color: '#34D399',
    Icon: SiMongodb,
    shell: 'inner',
  },
  {
    id: 'express',
    label: 'Express',
    color: '#CBD5E1',
    Icon: SiExpress,
    shell: 'inner',
  },
  {
    id: 'javascript',
    label: 'JavaScript',
    color: '#FACC15',
    Icon: SiJavascript,
    shell: 'middle',
  },
];

export const SHELL_CONFIGS = [
  {
    id: 'inner',
    radius: 2.2,
    speed: 0.28,
    axisTheta: Math.PI * 0.24,
    axisPhi: Math.PI * 0.43,
    thetaOffset: 0.4,
    tilt: [0.32, -0.18, 0.08],
    floatAmplitude: 0.05,
    floatSpeed: 1.2,
  },
  {
    id: 'middle',
    radius: 2.85,
    speed: -0.2,
    axisTheta: Math.PI * 0.66,
    axisPhi: Math.PI * 0.52,
    thetaOffset: 1.25,
    tilt: [-0.24, 0.3, -0.12],
    floatAmplitude: 0.06,
    floatSpeed: 0.95,
  },
  {
    id: 'outer',
    radius: 3.45,
    speed: 0.14,
    axisTheta: Math.PI * 1.14,
    axisPhi: Math.PI * 0.61,
    thetaOffset: 2.1,
    tilt: [0.18, 0.46, 0.18],
    floatAmplitude: 0.07,
    floatSpeed: 0.82,
  },
];
